### ISSUE TITLE
Create Socrata API calls

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-walkmaper#1]
One of the apparently more challenging aspects of this is the call to 311 data, but I already puzzled through the endpoints that we need to use in scoping to make sure this part was possible.

Here's an example:
`https://data.cityofnewyork.us/resource/erm2-nwe9.json?$where=complaint_type in('Catch Basin Complaint','Building Construction Complaint','Idling Vehicle','Trash or Recycling Storage Complaint','Dirty Sidewalk','Litter Basket Complaint','Bike Rack Complaint','Blocked Sidewalk or Street','Broken Sidewalk','Bus Stop Shelter Complaint','Chained Bike','Curb Complaint','Dead Tree','Dirty Sidewalk','Fallen Tree or Branch','LinkNYC','Littering','Newspaper Box Complaint','Outdoor Dining Complaint','Pay Phone Complaint','Pedestrian Ramp Complaint','Scaffold or Sidewalk Shed Complaint','Sidewalk Cellar Door Complaint','Sidewalk Collapsed','Sidewalk Grating Complaint','Sidewalk Utility Hardware Complaint','Snow or Ice on Sidewalk','Streetlight Complaint','Traffic or Pedestrian Signal Complaint','Tree Destruction','Tree Planting','Tree Pruning','Vendor Complaint','Car Service Complaint','Taxi Complaint','Bike Rack Complaint','City Vehicle Complaint') and created_date>='2019-09-01T00:00:00' and within_circle(location, 40.744961, -73.993118, 50)`

The differences to make this dynamic would be:
1. replace the `created_date>=` param with a calculated date of today minus 24 months
2. replace the `lat,lng` with the items coordinates from `within_circle(location, lat, lng, 50)`

**Comment by gregallensworth** [comment]
This is in place in #2 with some screenshots in #2 where we can address style & behavior for the data points.

I guess the only API-related question here is whether every one of these complaint types should be requested. For example, two-year-old complaints about a taxi driver or a street vendor "feel" out of place for a map about obstructions and disrepair. But that can be discussed in #2 with other talking points.

**Comment by gregallensworth** [comment]
- [x] add a clause to filter by `status != Closed`
