### ISSUE TITLE
Two Safari issues

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-walkmaper#4]
Of course this client uses Safari, and I hadn't tried anything in Safari 🙄 

## popups

I can't get the popups to appear in Safari, though also no console messages:
![image](https://user-images.githubusercontent.com/1423200/135929962-fd7e19c7-2269-478c-8386-1dc34045d1ec.png)

these work as expected in Chrome, Firefox, and Edge, but nothing in Safari

## 311 download
Chrome, Firefox, and Edge all behave properly for the CART and 311 downloads. Safari also works well for CARTO, but Safari just opens the CSV file in a new window:
![image](https://user-images.githubusercontent.com/1423200/135931413-f362cc38-76a5-4e1d-bc30-f769d13a725a.png)

Is there a way to force that to do a file download?

**Comment by gregallensworth** [comment]
Yeah, I figured that linking directly to the CSV wouldn't be reliable. Socrata sends a Content-type header, but not a Content-disposition header, so it's up to the browser to do whatever it finds appropriate... e.g. display it.

- [x] throw out the hyperlink approach and instead write something to fetch the CSV data via JSON
- [x] ... and stow the raw CSV / GeoJSON blob in memory instead
- [x] bring in something like fileSaver which allows in-memory blobs to behave like a download, so the in-memory CSV string is used instead

**Comment by gregallensworth** [comment]
Popups - Apparently this is a known bug in Leaflet 1.7.1 well over a year now.    https://stackoverflow.com/questions/65369083/popup-does-not-open-when-clicking-on-marker-safari

- [x] try the suggested workaround: add `tap: false` to L.Map constructor
- [x] note that someone else reports that `bindPopup()` continued to be flaky, but explicitly using `on('click')` on the marker seemed to work better

**Comment by gregallensworth** [comment]
Both done. I had to thrash around a bit, as I found some unexpected changes and merge conflicts in the code so had to work around those. But eventually things came together, I hope?

**Comment by danrademacher** [comment]
Looks good! Sorry, I should have mentioned I made some client-requested changes to the look of the downloads panel
